-- Funcion Escalar

--CREAR EL ESQUEMA. FN_NOMBRE DE LA FUNCION
CREATE OR ALTER FUNCTION ADCR.FN_NOMBREFUNCION
(
--PARAMETRO, TIPO DE DATO
@RESULTADO INT
)
RETURNS INT
AS
BEGIN
	DECLARE @CONTAR INT
	...
	RETURNS @CONTAR
END
GO